import 'dart:convert';

import 'package:meta/meta.dart';
import 'package:log_pilot/src/core/breadcrumb.dart';
import 'package:log_pilot/src/core/log_level.dart';

/// A structured log entry produced by LogPilot.
///
/// Every call to `LogPilot.info()`, `LogPilot.error()`, etc. produces a
/// [LogPilotRecord] that is sent to each [LogSink] registered in
/// [LogPilotConfig.sinks]. Records are also created for errors caught
/// by the global error zone.
///
/// ```dart
/// LogPilotConfig(
///   sinks: [
///     CallbackSink((record) {
///       print('${record.level}: ${record.message}');
///     }),
///   ],
/// )
/// ```
@immutable
class LogPilotRecord {
  const LogPilotRecord({
    required this.level,
    required this.timestamp,
    this.message,
    this.tag,
    this.caller,
    this.metadata,
    this.error,
    this.stackTrace,
    this.sessionId,
    this.traceId,
    this.errorId,
    this.breadcrumbs,
  });

  /// Severity level of this log entry.
  final LogLevel level;

  /// When this record was created.
  final DateTime timestamp;

  /// The resolved log message (after lazy evaluation).
  final String? message;

  /// Optional tag for categorization (e.g. `'auth'`, `'checkout'`).
  final String? tag;

  /// Clickable source location (e.g. `package:my_app/home.dart:42:8`).
  final String? caller;

  /// Structured key-value data attached to this log.
  final Map<String, dynamic>? metadata;

  /// The error object, if any.
  final Object? error;

  /// The stack trace associated with [error].
  final StackTrace? stackTrace;

  /// The app session identifier, auto-generated by [LogPilot.init] or
  /// [LogPilot.configure]. Use for correlating all logs from a single
  /// app launch with backend traces and crash reports.
  final String? sessionId;

  /// An optional per-request or per-operation trace ID.
  ///
  /// Set via [LogPilot.setTraceId] before starting an operation, then
  /// cleared via [LogPilot.clearTraceId] when done. All logs emitted
  /// while a trace ID is active carry it here.
  final String? traceId;

  /// A deterministic hash-based identifier for this error's signature.
  ///
  /// Only present on error and fatal records. Built from the error's
  /// runtime type, a normalized message pattern, and the top stack frame.
  /// Agents can reference errors by ID across debugging sessions:
  /// "Error `lk-e3a9f2` occurred 4 times in the last 60 seconds."
  final String? errorId;

  /// The trail of recent events leading up to this error.
  ///
  /// Only present on error and fatal records. Contains the last N
  /// breadcrumbs that were captured before this error occurred,
  /// providing immediate pre-crash context.
  final List<Breadcrumb>? breadcrumbs;

  /// Serialize this record to a JSON-compatible map.
  ///
  /// Useful for file logging, remote backends, and structured export.
  /// The [error] and [stackTrace] are converted to strings since they
  /// are not inherently JSON-serializable.
  Map<String, dynamic> toJson() => {
        'level': level.label,
        'timestamp': timestamp.toIso8601String(),
        if (sessionId != null) 'sessionId': sessionId,
        if (traceId != null) 'traceId': traceId,
        if (errorId != null) 'errorId': errorId,
        if (message != null) 'message': message,
        if (tag != null) 'tag': tag,
        if (caller != null) 'caller': caller,
        if (metadata != null) 'metadata': metadata,
        if (error != null) 'error': error.toString(),
        if (stackTrace != null) 'stackTrace': stackTrace.toString(),
        if (breadcrumbs != null && breadcrumbs!.isNotEmpty)
          'breadcrumbs': breadcrumbs!.map((b) => b.toJson()).toList(),
      };

  /// Encode this record as a single-line JSON string.
  ///
  /// Convenient for appending to log files where each line is one record.
  String toJsonString() => jsonEncode(toJson());

  /// Format this record as a compact, human-readable single line.
  ///
  /// Produces output like:
  /// `2026-03-28T14:23:01.456 [INFO] sid=abc123 [auth] User signed in`
  ///
  /// Stack traces are intentionally excluded for a compact one-line
  /// format. Use [toJson] for the full structured representation
  /// including stack traces.
  String toFormattedString() {
    final buffer = StringBuffer();
    buffer.write(timestamp.toIso8601String());
    buffer.write(' [${level.label}]');
    if (sessionId != null) buffer.write(' sid=$sessionId');
    if (traceId != null) buffer.write(' tid=$traceId');
    if (errorId != null) buffer.write(' eid=$errorId');
    if (tag != null) buffer.write(' [$tag]');
    if (message != null) buffer.write(' $message');
    if (error != null) buffer.write(' | Error: $error');
    if (metadata != null && metadata!.isNotEmpty) {
      buffer.write(' | ${jsonEncode(metadata)}');
    }
    return buffer.toString();
  }

  @override
  String toString() =>
      'LogPilotRecord(level: $level, message: $message, tag: $tag)';
}
